version: '3'
services:
  frontend:
    container_name: frontend-processador-de-consultas
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app/frontend
